name: "WebGL SDK Publish"

on:
    release:
        types: [published]

jobs:
    release:
        name: WebGL SDK Publish
        runs-on: ubuntu-latest
        steps:
            - name: WebGL SDK Checkout
              uses: actions/checkout@v2.3.5
           # - name: WebGL SDK Configure User
           #   run: git config --global user.name "Leia WebGL SDK"
           # - name: WebGL SDK Increment Version
           #   run: npm version patch
           # - name: WebGL SDK Commit Version
           #   run: git push
           # - name: WebGL SDK Create Tag
           #   id: create_tag
           #   uses: Klemensas/action-autotag@stable
           #   env:
           #       GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}" # This token is provided by Actions, you do not need to create your own token
           #   with:
           #       tag_message: "Automatic Build."
            - name: WebGL SDK Setup Nodejs
              uses: actions/setup-node@v2.4.1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: WebGL SDK Publish
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}} # This token is required for npm publishing. Create secret via your npm account.
           # - name: WebGL SDK Create Release
           #   uses: actions/create-release@v1
           #   env:
           #       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # This token is provided by Actions, you do not need to create your own token
           #   with:
           #       tag_name: "${{steps.create_tag.outputs.tagname}}"
           #       release_name: "Release ${{steps.create_tag.outputs.tagname}}"